### ISSUE TITLE
Missing `luzzu-lod-dataportal` dependency from Maven Central

### ISSUE THREAD

**Issue by GezimSejdiu** [Luzzu/Framework#1]
Hi @jerdeb ,

while building luzzu framework locally it wasn't able to resolve a dependency for `luzzu-lod-dataportal`.
```sh
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.487 s
[INFO] Finished at: 2018-11-20T11:37:35+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project luzzu-communications: Could not resolve dependencies for project io.github.luzzu:luzzu-communications:jar:4.0.0: Could not find artifact io.github.luzzu:luzzu-lod-dataportal:jar:4.0.0 in central (https://repo.maven.apache.org/maven2)
```
Is this dependency locally installed somehow or it is missing from the Maven Central.

The issue is related to: https://github.com/Luzzu/Framework/blob/master/luzzu-communications/pom.xml#L62,L66

Many thanks in advance for your help. 

Best regards,
Gezim

**Comment by jerdeb** [comment]
Ah right, I need to remove that from the pom as it is something I'm using
internally

**Comment by jerdeb** [comment]
@GezimSejdiu can you please pull and retry again? Should be fixed now

**Comment by GezimSejdiu** [comment]
Great! Yes, it is working now. Thanks for solving the issue.
