### ISSUE TITLE
Luzzu IO Module Error

### ISSUE THREAD

**Issue by oldray** [Luzzu/Framework#2]
Running io.github.luzzu.io.configuration.DeclerativeMetricCompilerTest
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/D:/maven-repository/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/maven-repository/org/slf4j/slf4j-jdk14/1.7.5/slf4j-jdk14-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:WARN Continuable parsing error 61 and column 23
log4j:WARN The content of element type "log4j:configuration" must match "(renderer*,throwableRenderer?,appender*,plugin*,(category|logger)*,root?,(categoryFactory|loggerFactory)?)".
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.069 sec <<< FAILURE!
Running io.github.luzzu.io.configuration.ExternalMetricLoaderTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec <<< FAILURE!
Running io.github.luzzu.io.impl.HDTProcessorTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.821 sec <<< FAILURE!
Running io.github.luzzu.io.impl.InMemoryProcessorTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.021 sec <<< FAILURE!
Running io.github.luzzu.io.impl.LargeNTGZStreamProcessorTest
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.032 sec <<< FAILURE!
Running io.github.luzzu.io.impl.SPARQLEndPointProcessorTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 23.136 sec <<< FAILURE!
Running io.github.luzzu.io.impl.StreamProcessorTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.016 sec <<< FAILURE!
Java HotSpot(TM) Client VM warning: ignoring option UseSplitVerifier; support was removed in 8.0

Results :

Failed tests:   getQualityMetricClassesTest(io.github.luzzu.io.configuration.ExternalMetricLoaderTest): expected:<2> but was:<0>

Tests in error:
  successfulExecutionTest(io.github.luzzu.io.configuration.DeclerativeMetricCompilerTest): 找不到目录: classes/
  successfulCompilationTest(io.github.luzzu.io.configuration.DeclerativeMetricCompilerTest): 找不到目录: classes/
  processingTest(io.github.luzzu.io.impl.HDTProcessorTest): 找不到目录: classes/
  setUpProcessTest(io.github.luzzu.io.impl.HDTProcessorTest): 找不到目录: classes/
  processingTest(io.github.luzzu.io.impl.InMemoryProcessorTest): 找不到目录: classes/
  setUpProcessTest(io.github.luzzu.io.impl.InMemoryProcessorTest): 找不到目录: classes/
  processingTest(io.github.luzzu.io.impl.LargeNTGZStreamProcessorTest): 找不到目录: classes/
  setUpProcessTest(io.github.luzzu.io.impl.LargeNTGZStreamProcessorTest): 找不到目录: classes/
  getPartialSubsetTest(io.github.luzzu.io.impl.LargeNTGZStreamProcessorTest): 找不到目录: classes/
  processingTest(io.github.luzzu.io.impl.SPARQLEndPointProcessorTest): 找不到目录: classes/
  setUpProcessTest(io.github.luzzu.io.impl.SPARQLEndPointProcessorTest): 找不到目录: classes/
  processingTest(io.github.luzzu.io.impl.StreamProcessorTest): 找不到目录: classes/
  setUpProcessTest(io.github.luzzu.io.impl.StreamProcessorTest): 找不到目录: classes/

Tests run: 14, Failures: 1, Errors: 13, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Luzzu 4.0.0:
[INFO]
[INFO] Luzzu .............................................. SUCCESS [  1.282 s]
[INFO] Luzzu Low-Level Operations Module .................. SUCCESS [  8.272 s]
[INFO] Luzzu Semantics Module ............................. SUCCESS [  3.711 s]
[INFO] Luzzu High-Level Operations Module ................. SUCCESS [  7.823 s]
[INFO] Luzzu Linked Data Quality Metric Commons ........... SUCCESS [  8.272 s]
[INFO] Luzzu Assessment Module ............................ SUCCESS [  8.827 s]
[INFO] Luzzu Annotations Module ........................... SUCCESS [  3.561 s]
[INFO] Luzzu Quality Metric Language ...................... SUCCESS [  3.439 s]
[INFO] Luzzu IO Module .................................... FAILURE [ 38.164 s]
[INFO] luzzu-webapp ....................................... SKIPPED
[INFO] Luzzu Communications Module ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:24 min
[INFO] Finished at: 2019-01-14T10:22:01+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project luzzu-io: There are test failures.
[ERROR]
[ERROR] Please refer to D:\works\luzzu\Framework-master\luzzu-io\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :luzzu-io

**Comment by jerdeb** [comment]
@oldray Please pull and check again. Should be working now
