### ISSUE TITLE
"Dataset profiles" / "Datasets page" has no defined route for /users

### ISSUE THREAD

**Issue by dbs** [Luzzu/Framework#4]
Clicking the "Dataset profiles" icon generates the following error due to a missing route for `/users/`:

    main.191f0924b63066cdf278.js:1 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'users'

**Comment by jerdeb** [comment]
Hi Dan, I should have fixed issues #3 and #4. For #4, please make sure you "force reload" the web app in your browser as otherwise the old scripts might still be in your cache.
