### ISSUE TITLE
Luzzu IO Module ..... FAILURE

### ISSUE THREAD

**Issue by shakeel26** [Luzzu/Framework#8]
I have tried Luzzu this as the latest version but got the same error as from the old version, when doing mvn clean installation in Framework, here is what the error, can you please tell me how can I add the required dependencies ? Thanks in Advance

[INFO] Luzzu IO Module .................................... FAILURE [  0.286 s]
[INFO] luzzu-webapp ....................................... SKIPPED
[INFO] Luzzu Communications Module ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.930 s
[INFO] Finished at: 2019-11-27T11:37:29+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project luzzu-io: Could not resolve dependencies for project io.github.luzzu:luzzu-io:jar:4.0.0: The following artifacts could not be resolved: org.rdfhdt:hdt-java-core:jar:2.1-SNAPSHOT, org.rdfhdt:hdt-jena:jar:2.1-SNAPSHOT: Could not find artifact org.rdfhdt:hdt-java-core:jar:2.1-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :luzzu-io

**Comment by jerdeb** [comment]
The problem there is that you do not have hdt built in your system. Please follow these steps (they are also in the readme file):
 1.   Open your command line.
 2.   git clone https://github.com/rdfhdt/hdt-java.git
 3.   cd hdt-java
 4.   mvn clean install

After building hdt, you will be able to build Luzzu. Unfortunately, hdt is not added to a maven repository.

Check if that works for you, otherwise, reopen this ticket.

**Comment by shakeel26** [comment]
hello, 
thank you for reply but I already have hdt built in system. I followed the instructions step wise from readme file. attcahed is the screenshot of the mvn clean install in hdt-java which is sucessfull. I only have issue for mvn clean install in Framework directory.
Please guide me to resolve the issue. Thanks in Advance

![luzzu 2](https://user-images.githubusercontent.com/45169340/69725564-c204b180-111e-11ea-84df-b31559e0984c.PNG)
![luzzu1](https://user-images.githubusercontent.com/45169340/69725565-c204b180-111e-11ea-9095-6ceb6672cb8e.PNG)
![luzzu3](https://user-images.githubusercontent.com/45169340/69725566-c29d4800-111e-11ea-96b9-1e1f9c311eee.PNG)
![luzzu4](https://user-images.githubusercontent.com/45169340/69725567-c29d4800-111e-11ea-8725-b6cc8c05fac6.PNG)

**Comment by jerdeb** [comment]
@ademarcrotti do you have time to look at this please?

**Comment by ademarcrotti** [comment]
Updated to latest hdt-java version, the system is building correctly now.

**Comment by shakeel26** [comment]
Thanks for reply, systems builds correctly again at cd hdt-java and mvn clean install which is fine. Problem is that system doesn't build when i run mvn clean install in cd Framework directory.  Error is attached here 
![luzzu failure](https://user-images.githubusercontent.com/45169340/70469966-592c1a80-1aca-11ea-983c-8e620e9739a6.PNG)
Thanks

**Comment by jerdeb** [comment]
Can you try `mvn clean install -X` and give us the log please?

**Comment by jerdeb** [comment]
I have just made a clean installation on a new docker image. It seems to be working for me. By the way, @ademarcrotti pushed some changes this morning. Please pull before compiling again.

<img width="488" alt="image" src="https://user-images.githubusercontent.com/2737057/70478215-d069aa80-1ada-11ea-8b12-3db292b826aa.png">

**Comment by shakeel26** [comment]
Thanks for reply, in my case also now build got successful. Unfortunately, after chmod +x start.sh when i run start.sh, I got again dependencies error and log can be seen in screenshot. Thanks 
![luzzu](https://user-images.githubusercontent.com/45169340/70553256-0cece300-1b7b-11ea-82f1-7444f76edf78.jpeg)

**Comment by federicodassereto** [comment]
Hi, 

I have the same error too. I did `mvn clean install ` and tried again but I find the same error as @shakeel26 .

I am able to run `start.sh` without sudo, but every time I try to compute something I occur in the error: 

> [Error - Error in generating quality metadata file for undefined] 2019-12-18 17:50:31: Read-only file system


Thank you!

**Comment by jerdeb** [comment]
@federicodassereto  What operating system are you using? The error you are point to seems that you are trying to save quality metadata in a folder which the OS does not allow you to do changes to. Check the property file (`luzzu-lowlevel-operations/src/main/resources/properties/luzzu.properties`) and check the location pointed by `QUALITY_METADATA_BASE_DIR`

**Comment by jerdeb** [comment]
@shakeel26 - can you please pull the latest change and try again. It seems that HDT changed their POM version between our push and your pull, and that is why it was giving you the error. `./start.sh` is working for me.

**Comment by brunopenteado** [comment]
Hi ,
I have a similar error. I tried to install both in Windows 10 and Ubuntu 18 and I got the same error.

Both HDT and Luzzu Framework were built with all their libraries.

I followed the steps from the wiki and I get this error, in both OS:

![error_Luzzu](https://user-images.githubusercontent.com/1571708/74110985-bfd3c000-4b6f-11ea-919c-c1a88a828957.png)


Any ideas?

**Comment by jerdeb** [comment]
Hi @brunopenteado. That seems to be a different error than the previous one. This one is related to glassfish (the library driving the web service). I think that is related to a different JDK/java version. What version are you using? Luzzu will run on java 1.8

**Comment by brunopenteado** [comment]
Hi @jerdeb, thanks for your response !  
When I run 'java -version' I get '12.0.2'.
Do I have to downgrade it?

**Comment by jerdeb** [comment]
Unfortunately yes. This is also described in the readme file:

In order to run Luzzu, you need to have Java 1.8 installed together with
maven.

**Comment by japeshmethuku17** [comment]
<img width="960" alt="2021-01-19" src="https://user-images.githubusercontent.com/65355382/105052728-1e840800-5a68-11eb-96cd-c5231d1fe906.png">

The execution of Luzzu IO module seems to fail. I have followed the same procedure as mentioned in the readme. Is there any resolutions for this?
PS: I am using Windows 10

**Comment by jerdeb** [comment]
This should be fixed now. See commit: b467a5cb0814d78b66981752cd7f254181c2bba4

**Comment by anouar25343** [comment]
The execution of Luzzu IO module seems to fail. I have followed the same procedure as mentioned in the readme. Is there any resolutions for this?
PS: I am using ubuntu-22.04





[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Luzzu 4.0.0:
[INFO] 
[INFO] Luzzu .............................................. SUCCESS [  3.084 s]
[INFO] Luzzu Low-Level Operations Module .................. SUCCESS [ 37.980 s]
[INFO] Luzzu Semantics Module ............................. SUCCESS [  1.106 s]
[INFO] Luzzu High-Level Operations Module ................. SUCCESS [  1.113 s]
[INFO] Luzzu Linked Data Quality Metric Commons ........... SUCCESS [  1.781 s]
[INFO] Luzzu Assessment Module ............................ SUCCESS [  0.656 s]
[INFO] Luzzu Annotations Module ........................... SUCCESS [  0.680 s]
[INFO] Luzzu Quality Metric Language ...................... SUCCESS [  1.114 s]
[INFO] Luzzu IO Module .................................... FAILURE [ 14.791 s]
[INFO] luzzu-webapp ....................................... SKIPPED
[INFO] Luzzu Communications Module ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:02 min
[INFO] Finished at: 2024-04-20T14:45:44+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project luzzu-io: Could not resolve dependencies for project io.github.luzzu:luzzu-io:jar:4.0.0: The following artifacts could not be resolved: org.rdfhdt:hdt-java-core:jar:2.1.3-SNAPSHOT, org.rdfhdt:hdt-jena:jar:2.1.3-SNAPSHOT: Could not find artifact org.rdfhdt:hdt-java-core:jar:2.1.3-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :luzzu-io

**Comment by anouar25343** [comment]
The execution of Luzzu IO module seems to fail. I have followed the same procedure as mentioned in the readme. Is there any resolutions for this?
PS: I am using ubuntu-22.04

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Luzzu 4.0.0:
[INFO]
[INFO] Luzzu .............................................. SUCCESS [ 3.084 s]
[INFO] Luzzu Low-Level Operations Module .................. SUCCESS [ 37.980 s]
[INFO] Luzzu Semantics Module ............................. SUCCESS [ 1.106 s]
[INFO] Luzzu High-Level Operations Module ................. SUCCESS [ 1.113 s]
[INFO] Luzzu Linked Data Quality Metric Commons ........... SUCCESS [ 1.781 s]
[INFO] Luzzu Assessment Module ............................ SUCCESS [ 0.656 s]
[INFO] Luzzu Annotations Module ........................... SUCCESS [ 0.680 s]
[INFO] Luzzu Quality Metric Language ...................... SUCCESS [ 1.114 s]
[INFO] Luzzu IO Module .................................... FAILURE [ 14.791 s]
[INFO] luzzu-webapp ....................................... SKIPPED
[INFO] Luzzu Communications Module ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:02 min
[INFO] Finished at: 2024-04-20T14:45:44+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project luzzu-io: Could not resolve dependencies for project io.github.luzzu:luzzu-io:jar:4.0.0: The following artifacts could not be resolved: org.rdfhdt:hdt-java-core:jar:2.1.3-SNAPSHOT, org.rdfhdt:hdt-jena:jar:2.1.3-SNAPSHOT: Could not find artifact org.rdfhdt:hdt-java-core:jar:2.1.3-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR] mvn -rf :luzzu-io
